<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Create' => 'Crea',
    'Directory could not be created!' => 'Impossibile creare la cartella',
    'Files were not accepted. (Size is too big?)' => 'I files non sono stati caricati. (Dimensioni troppo grandi?)',
    'Cancel' => 'Annulla',
    'Create directory' => 'Crea cartella',
    'Date' => 'Data',
    'Delete' => 'Elimina',
    'Documents' => 'Documenti',
    'File upload failed!' => 'Upload del file fallito!',
    'Name' => 'Nome',
    'Size' => 'Dimensione',
    'Something went wrong!' => 'Qualcosa non ha funzionato!',
    'Upload' => 'Carica files',
];
